version: "3"
services:
  web:
    build:
        context: .
        dockerfile: ./Dockerfile
        args:
          ENV_FILE: ".env.dev"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

  clickhouse:
    image: yandex/clickhouse-server:21.3.13.9-alpine
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nproc: 262144
      nofile:
        soft: 262144
        hard: 262144

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: kafka # add to /etc/hosts
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  clickhouse_data: